[app_settings]
app_version = "0.1.0"
app_name = "lms"
app_host = "0.0.0.0"
app_port = 8000


[db_settings]
db_name = "postgres"
db_user = "user"
db_password = "password"
db_host = "db"
db_port = 5432

[auth_settings]
secret_key = "lms"
algorithm = "HS256"
access_token_expire_minutes = 30
refresh_token_expire_days = 7

[redis_settings]
redis_host = "redis"
redis_port = 6379
redis_db = 0
redis_password = ""